import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1779180880498 implements MigrationInterface {
    name = 'Init1779180880498'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" DROP CONSTRAINT "ai_feedbacks_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" DROP CONSTRAINT "ai_feedbacks_classification_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP CONSTRAINT "trash_classifications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" DROP CONSTRAINT "accepted_waste_types_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" DROP CONSTRAINT "partner_role_types_partner_profile_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" DROP CONSTRAINT "partner_profiles_approved_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" DROP CONSTRAINT "partner_profiles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" DROP CONSTRAINT "location_capabilities_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" DROP CONSTRAINT "collection_location_profiles_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" DROP CONSTRAINT "collection_qr_sessions_issued_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" DROP CONSTRAINT "collection_qr_sessions_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "locations_verified_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "locations_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "locations_partner_profile_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "dropoff_transactions_verified_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "dropoff_transactions_accepted_waste_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "dropoff_transactions_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "dropoff_transactions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "dropoff_transactions_qr_session_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "point_transactions" DROP CONSTRAINT "point_transactions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP CONSTRAINT "reward_pickup_options_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP CONSTRAINT "reward_pickup_options_reward_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP CONSTRAINT "rewards_partner_profile_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "redemptions" DROP CONSTRAINT "redemptions_reward_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "redemptions" DROP CONSTRAINT "redemptions_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_feedbacks_classification_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_feedbacks_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trash_classifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accepted_waste_types_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_partner_role_types_partner_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_partner_profiles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_partner_profiles_approval_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_location_capabilities_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_location_capabilities_capability"`);
        await queryRunner.query(`DROP INDEX "public"."idx_collection_location_profiles_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_collection_location_profiles_site_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_collection_qr_sessions_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_collection_qr_sessions_qr_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_collection_qr_sessions_expired_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_locations_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_locations_verified_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_locations_partner_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_locations_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dropoff_transactions_qr_session_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dropoff_transactions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dropoff_transactions_verified_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dropoff_transactions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dropoff_transactions_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dropoff_transactions_accepted_waste_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_point_transactions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reward_pickup_options_reward_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reward_pickup_options_location_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rewards_partner_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rewards_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_redemptions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_redemptions_reward_id"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP CONSTRAINT "trash_classifications_confidence_check"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "dropoff_transactions_quantity_value_check"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "dropoff_transactions_points_awarded_check"`);
        await queryRunner.query(`ALTER TABLE "point_transactions" DROP CONSTRAINT "point_transactions_balance_after_check"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP CONSTRAINT "rewards_points_cost_check"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP CONSTRAINT "rewards_stock_check"`);
        await queryRunner.query(`ALTER TABLE "redemptions" DROP CONSTRAINT "redemptions_points_spent_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_points_balance_check"`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" DROP CONSTRAINT "uq_accepted_waste_types_location_waste"`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" DROP CONSTRAINT "partner_role_types_partner_profile_id_role_type_key"`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" DROP CONSTRAINT "location_capabilities_location_id_capability_key"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP CONSTRAINT "reward_pickup_options_reward_id_location_id_key"`);
        await queryRunner.query(`CREATE TYPE "public"."point_rules_event_type_enum" AS ENUM('CLASSIFICATION_CORRECT', 'DROPOFF_CONFIRMED', 'REDEMPTION', 'MANUAL_ADJUST')`);
        await queryRunner.query(`CREATE TABLE "point_rules" ("id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "description" text, "event_type" "public"."point_rules_event_type_enum" NOT NULL, "points" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" uuid, CONSTRAINT "PK_dc4e75d7a149814c24e45778709" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1d5c186db00bff2c21dde61606" ON "point_rules" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."admin_audit_action" AS ENUM('USER_STATUS_CHANGE', 'USER_PROFILE_UPDATE', 'PARTNER_APPROVAL', 'PARTNER_ROLES_UPDATE', 'REWARD_CREATE', 'REWARD_UPDATE', 'REWARD_DELETE', 'REDEMPTION_STATUS_UPDATE', 'COLLECTION_POINT_CREATE', 'COLLECTION_POINT_UPDATE', 'COLLECTION_POINT_DELETE', 'POINTS_ADJUST')`);
        await queryRunner.query(`CREATE TABLE "admin_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admin_id" uuid NOT NULL, "admin_email" character varying(255) NOT NULL, "target_user_id" uuid, "action" "public"."admin_audit_action" NOT NULL, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de7a8fc2fbb525484c71a86bb96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_01a78e07962ed72eaf9ccae990" ON "admin_audit_logs" ("admin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_432af0bb419f00121f90231643" ON "admin_audit_logs" ("target_user_id") `);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" DROP COLUMN "issued_by"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "opening_hours"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "qr_session_id"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "check_in_latitude"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "check_in_longitude"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "distance_meters"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "receipt_code"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP COLUMN "start_at"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP COLUMN "end_at"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP COLUMN "thumbnail_url"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP COLUMN "terms"`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ADD "corrected_label" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "user_latitude" double precision`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "user_longitude" double precision`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "distance_km" double precision`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ADD "reason_code" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ALTER COLUMN "classification_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ALTER COLUMN "status" SET DEFAULT 'SUCCESS'`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP COLUMN "model_name"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD "model_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP COLUMN "model_version"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD "model_version" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP COLUMN "result_json"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD "result_json" json`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ALTER COLUMN "waste_type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."partner_role_type" RENAME TO "partner_role_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."partner_role_types_role_type_enum" AS ENUM('COLLECTOR', 'REWARD_PROVIDER')`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ALTER COLUMN "role_type" TYPE "public"."partner_role_types_role_type_enum" USING "role_type"::"text"::"public"."partner_role_types_role_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."partner_role_type_old"`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ALTER COLUMN "partner_profile_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."partner_approval_status" RENAME TO "partner_approval_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."partner_profiles_approval_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "approval_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "approval_status" TYPE "public"."partner_profiles_approval_status_enum" USING "approval_status"::"text"::"public"."partner_profiles_approval_status_enum"`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "approval_status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."partner_approval_status_old"`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."location_capability_type" RENAME TO "location_capability_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."location_capabilities_capability_enum" AS ENUM('COLLECTION', 'REWARD_PICKUP')`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ALTER COLUMN "capability" TYPE "public"."location_capabilities_capability_enum" USING "capability"::"text"::"public"."location_capabilities_capability_enum"`);
        await queryRunner.query(`DROP TYPE "public"."location_capability_type_old"`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ALTER COLUMN "location_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."collection_site_type" RENAME TO "collection_site_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."collection_location_profiles_site_type_enum" AS ENUM('MACHINE', 'COUNTER', 'BIN')`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "site_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "site_type" TYPE "public"."collection_location_profiles_site_type_enum" USING (CASE WHEN "site_type"::text IN ('MACHINE', 'COUNTER', 'BIN') THEN "site_type"::text ELSE 'BIN' END)::"public"."collection_location_profiles_site_type_enum"`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "site_type" SET DEFAULT 'BIN'`);
        await queryRunner.query(`DROP TYPE "public"."collection_site_type_old"`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "requires_staff_confirmation" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "location_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" DROP CONSTRAINT "collection_qr_sessions_qr_token_key"`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ALTER COLUMN "qr_token" TYPE character varying(255)`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ALTER COLUMN "location_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "contact_phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "quantity_value" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "quantity_unit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "points_awarded" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "points_awarded" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TYPE "public"."point_transaction_type" RENAME TO "point_transaction_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."point_transactions_type_enum" AS ENUM('EARN', 'SPEND', 'ADJUST')`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "type" TYPE "public"."point_transactions_type_enum" USING "type"::"text"::"public"."point_transactions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."point_transaction_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."point_source_type" RENAME TO "point_source_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."point_transactions_source_type_enum" AS ENUM('TRASH_CLASSIFICATION', 'DROPOFF_TRANSACTION', 'REDEMPTION', 'ADMIN', 'QUIZ')`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "source_type" TYPE "public"."point_transactions_source_type_enum" USING "source_type"::"text"::"public"."point_transactions_source_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."point_source_type_old"`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "source_type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ALTER COLUMN "reward_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ALTER COLUMN "location_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "points_cost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "stock" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "redemptions" ALTER COLUMN "points_spent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "redemptions" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "redemptions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" TYPE character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" TYPE character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "full_name" TYPE character varying(100) USING COALESCE(full_name, '')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "full_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'PARTNER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status" RENAME TO "user_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'LOCKED', 'BANNED')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."users_status_enum" USING "status"::"text"::"public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."user_status_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_a900c4f08e13898891a9a65acb" ON "ai_feedbacks" ("classification_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b39a7bae5d1a546028bfa7bbb0" ON "ai_feedbacks" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b28cef44f56f81a93efe3638af" ON "trash_classifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_56702c8b9e89190347707b7555" ON "point_transactions" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ADD CONSTRAINT "FK_a900c4f08e13898891a9a65acb7" FOREIGN KEY ("classification_id") REFERENCES "trash_classifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ADD CONSTRAINT "FK_b39a7bae5d1a546028bfa7bbb0a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD CONSTRAINT "FK_b28cef44f56f81a93efe3638af0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ADD CONSTRAINT "FK_79688f9030ced5942afd256795c" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ADD CONSTRAINT "FK_f676a859143a90a8c606a80caf1" FOREIGN KEY ("partner_profile_id") REFERENCES "partner_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ADD CONSTRAINT "FK_2d11522f31ddd947e017fee12d8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ADD CONSTRAINT "FK_a6cca26d97eead9346296ca029f" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ADD CONSTRAINT "FK_14560d3a89e2e3b030c2a431864" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ADD CONSTRAINT "FK_d6ca076a141fd0e78fea70af576" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_190a7ee60db34ef946627cbbe9f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_27145f90a0a487d1812b0ecffef" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_4ac4aa3242fd74629f16b113ff6" FOREIGN KEY ("partner_profile_id") REFERENCES "partner_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "FK_14e606b8d60651bd9f9379d03f1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "FK_540eba1b8c30935d615e513b8d5" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "FK_2d1f9139ec426dd92a53f5012a0" FOREIGN KEY ("accepted_waste_type_id") REFERENCES "accepted_waste_types"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "FK_1fa6b0c62a4806c6c70c87834be" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_rules" ADD CONSTRAINT "FK_a931f7a411170c8f4bf02f63511" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ADD CONSTRAINT "FK_56702c8b9e89190347707b75552" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD CONSTRAINT "FK_28309abd637aa7d4a63e2c617e8" FOREIGN KEY ("reward_id") REFERENCES "rewards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD CONSTRAINT "FK_bf65a98b6b3a7c9e794ddc2a76d" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD CONSTRAINT "FK_d379ea1aa105a4e69a4318450da" FOREIGN KEY ("partner_profile_id") REFERENCES "partner_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "redemptions" ADD CONSTRAINT "FK_c59b27ed1a764e578add290572c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "redemptions" ADD CONSTRAINT "FK_e845e4dbdf77458f29473e5e0cf" FOREIGN KEY ("reward_id") REFERENCES "rewards"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "redemptions" DROP CONSTRAINT "FK_e845e4dbdf77458f29473e5e0cf"`);
        await queryRunner.query(`ALTER TABLE "redemptions" DROP CONSTRAINT "FK_c59b27ed1a764e578add290572c"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP CONSTRAINT "FK_d379ea1aa105a4e69a4318450da"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP CONSTRAINT "FK_bf65a98b6b3a7c9e794ddc2a76d"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP CONSTRAINT "FK_28309abd637aa7d4a63e2c617e8"`);
        await queryRunner.query(`ALTER TABLE "point_transactions" DROP CONSTRAINT "FK_56702c8b9e89190347707b75552"`);
        await queryRunner.query(`ALTER TABLE "point_rules" DROP CONSTRAINT "FK_a931f7a411170c8f4bf02f63511"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "FK_1fa6b0c62a4806c6c70c87834be"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "FK_2d1f9139ec426dd92a53f5012a0"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "FK_540eba1b8c30935d615e513b8d5"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP CONSTRAINT "FK_14e606b8d60651bd9f9379d03f1"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_4ac4aa3242fd74629f16b113ff6"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_27145f90a0a487d1812b0ecffef"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_190a7ee60db34ef946627cbbe9f"`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" DROP CONSTRAINT "FK_d6ca076a141fd0e78fea70af576"`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" DROP CONSTRAINT "FK_14560d3a89e2e3b030c2a431864"`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" DROP CONSTRAINT "FK_a6cca26d97eead9346296ca029f"`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" DROP CONSTRAINT "FK_2d11522f31ddd947e017fee12d8"`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" DROP CONSTRAINT "FK_f676a859143a90a8c606a80caf1"`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" DROP CONSTRAINT "FK_79688f9030ced5942afd256795c"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP CONSTRAINT "FK_b28cef44f56f81a93efe3638af0"`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" DROP CONSTRAINT "FK_b39a7bae5d1a546028bfa7bbb0a"`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" DROP CONSTRAINT "FK_a900c4f08e13898891a9a65acb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56702c8b9e89190347707b7555"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b28cef44f56f81a93efe3638af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b39a7bae5d1a546028bfa7bbb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a900c4f08e13898891a9a65acb"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_old" AS ENUM('ACTIVE', 'LOCKED')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."user_status_old" USING "status"::"text"::"public"."user_status_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_old" RENAME TO "user_status"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('USER', 'PARTNER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "full_name" TYPE text`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "full_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" TYPE text`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" TYPE text`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "redemptions" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "redemptions" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "redemptions" ALTER COLUMN "points_spent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "stock" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "points_cost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rewards" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ALTER COLUMN "location_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ALTER COLUMN "reward_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "source_type" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."point_source_type_old" AS ENUM('TRASH_CLASSIFICATION', 'DROPOFF_TRANSACTION', 'REDEMPTION', 'ADMIN', 'QUIZ')`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "source_type" TYPE "public"."point_source_type_old" USING "source_type"::"text"::"public"."point_source_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."point_transactions_source_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."point_source_type_old" RENAME TO "point_source_type"`);
        await queryRunner.query(`CREATE TYPE "public"."point_transaction_type_old" AS ENUM('EARN', 'SPEND', 'ADJUST')`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "type" TYPE "public"."point_transaction_type_old" USING "type"::"text"::"public"."point_transaction_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."point_transactions_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."point_transaction_type_old" RENAME TO "point_transaction_type"`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "points_awarded" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "points_awarded" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "quantity_unit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ALTER COLUMN "quantity_value" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "contact_phone" text`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ALTER COLUMN "location_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ALTER COLUMN "qr_token" TYPE text`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ADD CONSTRAINT "collection_qr_sessions_qr_token_key" UNIQUE ("qr_token")`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "location_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "requires_staff_confirmation" SET DEFAULT true`);
        await queryRunner.query(`CREATE TYPE "public"."collection_site_type_old" AS ENUM('GENERAL_WASTE', 'RECYCLING', 'BATTERY', 'E_WASTE', 'HAZARDOUS', 'DONATION', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "site_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "site_type" TYPE "public"."collection_site_type_old" USING "site_type"::"text"::"public"."collection_site_type_old"`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ALTER COLUMN "site_type" SET DEFAULT 'RECYCLING'`);
        await queryRunner.query(`DROP TYPE "public"."collection_location_profiles_site_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."collection_site_type_old" RENAME TO "collection_site_type"`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ALTER COLUMN "location_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."location_capability_type_old" AS ENUM('COLLECTION', 'REWARD_PICKUP')`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ALTER COLUMN "capability" TYPE "public"."location_capability_type_old" USING "capability"::"text"::"public"."location_capability_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."location_capabilities_capability_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."location_capability_type_old" RENAME TO "location_capability_type"`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."partner_approval_status_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "approval_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "approval_status" TYPE "public"."partner_approval_status_old" USING "approval_status"::"text"::"public"."partner_approval_status_old"`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ALTER COLUMN "approval_status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."partner_profiles_approval_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."partner_approval_status_old" RENAME TO "partner_approval_status"`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ALTER COLUMN "partner_profile_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."partner_role_type_old" AS ENUM('COLLECTOR', 'REWARD_PROVIDER')`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ALTER COLUMN "role_type" TYPE "public"."partner_role_type_old" USING "role_type"::"text"::"public"."partner_role_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."partner_role_types_role_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."partner_role_type_old" RENAME TO "partner_role_type"`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ALTER COLUMN "waste_type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP COLUMN "result_json"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD "result_json" jsonb`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP COLUMN "model_version"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD "model_version" text`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" DROP COLUMN "model_name"`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD "model_name" text`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ALTER COLUMN "classification_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "point_transactions" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "point_transactions" DROP COLUMN "reason_code"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "distance_km"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "user_longitude"`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" DROP COLUMN "user_latitude"`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" DROP COLUMN "corrected_label"`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD "terms" text`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD "thumbnail_url" text`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD "type" text`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD "end_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD "start_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "receipt_code" text`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "distance_meters" double precision`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "check_in_longitude" double precision`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "check_in_latitude" double precision`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD "qr_session_id" uuid`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "opening_hours" text`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ADD "issued_by" uuid`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`DROP INDEX "public"."IDX_432af0bb419f00121f90231643"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01a78e07962ed72eaf9ccae990"`);
        await queryRunner.query(`DROP TABLE "admin_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."admin_audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d5c186db00bff2c21dde61606"`);
        await queryRunner.query(`DROP TABLE "point_rules"`);
        await queryRunner.query(`DROP TYPE "public"."point_rules_event_type_enum"`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD CONSTRAINT "reward_pickup_options_reward_id_location_id_key" UNIQUE ("reward_id", "location_id")`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ADD CONSTRAINT "location_capabilities_location_id_capability_key" UNIQUE ("location_id", "capability")`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ADD CONSTRAINT "partner_role_types_partner_profile_id_role_type_key" UNIQUE ("partner_profile_id", "role_type")`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ADD CONSTRAINT "uq_accepted_waste_types_location_waste" UNIQUE ("location_id", "waste_type")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_points_balance_check" CHECK ((points_balance >= 0))`);
        await queryRunner.query(`ALTER TABLE "redemptions" ADD CONSTRAINT "redemptions_points_spent_check" CHECK ((points_spent >= 0))`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD CONSTRAINT "rewards_stock_check" CHECK ((stock >= 0))`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD CONSTRAINT "rewards_points_cost_check" CHECK ((points_cost >= 0))`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ADD CONSTRAINT "point_transactions_balance_after_check" CHECK ((balance_after >= 0))`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "dropoff_transactions_points_awarded_check" CHECK ((points_awarded >= 0))`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "dropoff_transactions_quantity_value_check" CHECK ((quantity_value > (0)::double precision))`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD CONSTRAINT "trash_classifications_confidence_check" CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))`);
        await queryRunner.query(`CREATE INDEX "idx_redemptions_reward_id" ON "redemptions" ("reward_id") `);
        await queryRunner.query(`CREATE INDEX "idx_redemptions_user_id" ON "redemptions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rewards_status" ON "rewards" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_rewards_partner_profile_id" ON "rewards" ("partner_profile_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reward_pickup_options_location_id" ON "reward_pickup_options" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reward_pickup_options_reward_id" ON "reward_pickup_options" ("reward_id") `);
        await queryRunner.query(`CREATE INDEX "idx_point_transactions_user_id" ON "point_transactions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_dropoff_transactions_accepted_waste_type_id" ON "dropoff_transactions" ("accepted_waste_type_id") `);
        await queryRunner.query(`CREATE INDEX "idx_dropoff_transactions_location_id" ON "dropoff_transactions" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "idx_dropoff_transactions_user_id" ON "dropoff_transactions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_dropoff_transactions_verified_by" ON "dropoff_transactions" ("verified_by") `);
        await queryRunner.query(`CREATE INDEX "idx_dropoff_transactions_status" ON "dropoff_transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_dropoff_transactions_qr_session_id" ON "dropoff_transactions" ("qr_session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_locations_status" ON "locations" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_locations_partner_profile_id" ON "locations" ("partner_profile_id") `);
        await queryRunner.query(`CREATE INDEX "idx_locations_verified_by" ON "locations" ("verified_by") `);
        await queryRunner.query(`CREATE INDEX "idx_locations_created_by" ON "locations" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "idx_collection_qr_sessions_expired_at" ON "collection_qr_sessions" ("expired_at") `);
        await queryRunner.query(`CREATE INDEX "idx_collection_qr_sessions_qr_token" ON "collection_qr_sessions" ("qr_token") `);
        await queryRunner.query(`CREATE INDEX "idx_collection_qr_sessions_location_id" ON "collection_qr_sessions" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "idx_collection_location_profiles_site_type" ON "collection_location_profiles" ("site_type") `);
        await queryRunner.query(`CREATE INDEX "idx_collection_location_profiles_location_id" ON "collection_location_profiles" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "idx_location_capabilities_capability" ON "location_capabilities" ("capability") `);
        await queryRunner.query(`CREATE INDEX "idx_location_capabilities_location_id" ON "location_capabilities" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "idx_partner_profiles_approval_status" ON "partner_profiles" ("approval_status") `);
        await queryRunner.query(`CREATE INDEX "idx_partner_profiles_user_id" ON "partner_profiles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_partner_role_types_partner_profile_id" ON "partner_role_types" ("partner_profile_id") `);
        await queryRunner.query(`CREATE INDEX "idx_accepted_waste_types_location_id" ON "accepted_waste_types" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trash_classifications_user_id" ON "trash_classifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ai_feedbacks_user_id" ON "ai_feedbacks" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ai_feedbacks_classification_id" ON "ai_feedbacks" ("classification_id") `);
        await queryRunner.query(`ALTER TABLE "redemptions" ADD CONSTRAINT "redemptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "redemptions" ADD CONSTRAINT "redemptions_reward_id_fkey" FOREIGN KEY ("reward_id") REFERENCES "rewards"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD CONSTRAINT "rewards_partner_profile_id_fkey" FOREIGN KEY ("partner_profile_id") REFERENCES "partner_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD CONSTRAINT "reward_pickup_options_reward_id_fkey" FOREIGN KEY ("reward_id") REFERENCES "rewards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward_pickup_options" ADD CONSTRAINT "reward_pickup_options_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_transactions" ADD CONSTRAINT "point_transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "dropoff_transactions_qr_session_id_fkey" FOREIGN KEY ("qr_session_id") REFERENCES "collection_qr_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "dropoff_transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "dropoff_transactions_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "dropoff_transactions_accepted_waste_type_id_fkey" FOREIGN KEY ("accepted_waste_type_id") REFERENCES "accepted_waste_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dropoff_transactions" ADD CONSTRAINT "dropoff_transactions_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "locations_partner_profile_id_fkey" FOREIGN KEY ("partner_profile_id") REFERENCES "partner_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "locations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "locations_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ADD CONSTRAINT "collection_qr_sessions_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_qr_sessions" ADD CONSTRAINT "collection_qr_sessions_issued_by_fkey" FOREIGN KEY ("issued_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_location_profiles" ADD CONSTRAINT "collection_location_profiles_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_capabilities" ADD CONSTRAINT "location_capabilities_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ADD CONSTRAINT "partner_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_profiles" ADD CONSTRAINT "partner_profiles_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_role_types" ADD CONSTRAINT "partner_role_types_partner_profile_id_fkey" FOREIGN KEY ("partner_profile_id") REFERENCES "partner_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accepted_waste_types" ADD CONSTRAINT "accepted_waste_types_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trash_classifications" ADD CONSTRAINT "trash_classifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ADD CONSTRAINT "ai_feedbacks_classification_id_fkey" FOREIGN KEY ("classification_id") REFERENCES "trash_classifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_feedbacks" ADD CONSTRAINT "ai_feedbacks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
