import type { Location, CollectionTransaction } from './types';

export const MOCK_LOCATIONS: Location[] = [
  {
    id: 'loc-001',
    name: 'Trạm thu gom Quận 1',
    type: 'COLLECTION_POINT',
    address: '123 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
    contactPhone: '0901234567',
    latitude: 10.773865,
    longitude: 106.701957,
    status: 'APPROVED',
    capabilities: ['COLLECTION', 'REWARD_PICKUP'],
    acceptedWasteTypes: [
      { wasteType: 'PLASTIC', conditionNote: 'Rửa sạch, không dính thức ăn' },
      { wasteType: 'PAPER', conditionNote: 'Không ướt' },
      { wasteType: 'METAL' },
      { wasteType: 'GLASS', conditionNote: 'Không bể vỡ' },
    ],
    collectionProfile: {
      siteType: 'COUNTER',
      instructions: 'Mang rác đến quầy tiếp nhận tầng 1, nhân viên sẽ hỗ trợ phân loại và cân.',
      requiresStaffConfirmation: true,
    },
    createdAt: '2026-03-15T08:30:00Z',
    updatedAt: '2026-05-10T14:20:00Z',
  },
  {
    id: 'loc-002',
    name: 'Thùng rác thông minh ĐH Bách Khoa',
    type: 'BIN',
    address: '268 Lý Thường Kiệt, Phường 14, Quận 10, TP.HCM',
    contactPhone: '0287654321',
    latitude: 10.772060,
    longitude: 106.657791,
    status: 'APPROVED',
    capabilities: ['COLLECTION'],
    acceptedWasteTypes: [
      { wasteType: 'PLASTIC' },
      { wasteType: 'PAPER' },
      { wasteType: 'BATTERY', conditionNote: 'Pin AA, AAA, điện thoại' },
    ],
    collectionProfile: {
      siteType: 'MACHINE',
      instructions: 'Quét mã QR trên thùng, bỏ rác vào ngăn tương ứng. Hệ thống tự động cân và cấp điểm.',
      requiresStaffConfirmation: false,
    },
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-05-18T09:15:00Z',
  },
  {
    id: 'loc-003',
    name: 'Trung tâm tái chế Quận 7',
    type: 'CENTER',
    address: '45 Nguyễn Lương Bằng, Phường Tân Phú, Quận 7, TP.HCM',
    contactPhone: '0912345678',
    latitude: 10.729400,
    longitude: 106.721700,
    status: 'APPROVED',
    capabilities: ['COLLECTION', 'REWARD_PICKUP'],
    acceptedWasteTypes: [
      { wasteType: 'PLASTIC', conditionNote: 'Tất cả loại nhựa' },
      { wasteType: 'PAPER' },
      { wasteType: 'METAL' },
      { wasteType: 'GLASS' },
      { wasteType: 'BATTERY' },
      { wasteType: 'OTHER', conditionNote: 'Liên hệ trước nếu rác đặc biệt' },
    ],
    collectionProfile: {
      siteType: 'COUNTER',
      instructions: 'Mở cửa 7h-17h. Mang rác đến khu tiếp nhận cổng chính, xuất trình mã QR để nhận điểm.',
      requiresStaffConfirmation: true,
    },
    createdAt: '2026-01-10T07:00:00Z',
    updatedAt: '2026-05-15T16:45:00Z',
  },
  {
    id: 'loc-004',
    name: 'Điểm thu gom Phú Nhuận',
    type: 'COLLECTION_POINT',
    address: '200 Phan Xích Long, Phường 2, Quận Phú Nhuận, TP.HCM',
    contactPhone: '0933456789',
    latitude: 10.799500,
    longitude: 106.680300,
    status: 'PENDING',
    capabilities: ['COLLECTION'],
    acceptedWasteTypes: [
      { wasteType: 'PLASTIC' },
      { wasteType: 'PAPER' },
    ],
    collectionProfile: {
      siteType: 'COUNTER',
      instructions: 'Điểm mới, đang chờ admin duyệt.',
      requiresStaffConfirmation: true,
    },
    createdAt: '2026-05-17T14:30:00Z',
    updatedAt: '2026-05-17T14:30:00Z',
  },
  {
    id: 'loc-005',
    name: 'Trạm Bình Thạnh',
    type: 'COLLECTION_POINT',
    address: '78 Đinh Bộ Lĩnh, Phường 26, Quận Bình Thạnh, TP.HCM',
    contactPhone: '0944567890',
    latitude: 10.810200,
    longitude: 106.711500,
    status: 'INACTIVE',
    capabilities: ['COLLECTION'],
    acceptedWasteTypes: [
      { wasteType: 'PLASTIC' },
      { wasteType: 'METAL' },
    ],
    collectionProfile: {
      siteType: 'BIN',
      instructions: 'Tạm ngưng hoạt động để bảo trì.',
      requiresStaffConfirmation: false,
    },
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-05-12T11:00:00Z',
  },
  {
    id: 'loc-006',
    name: 'Điểm thu gom Gò Vấp',
    type: 'COLLECTION_POINT',
    address: '300 Quang Trung, Phường 10, Quận Gò Vấp, TP.HCM',
    contactPhone: '0955678901',
    latitude: 10.838500,
    longitude: 106.664200,
    status: 'REJECTED',
    capabilities: ['COLLECTION'],
    acceptedWasteTypes: [
      { wasteType: 'OTHER' },
    ],
    createdAt: '2026-05-05T16:00:00Z',
    updatedAt: '2026-05-06T09:00:00Z',
  },
  {
    id: 'loc-007',
    name: 'Thùng rác Công viên Tao Đàn',
    type: 'BIN',
    address: 'Công viên Tao Đàn, Quận 1, TP.HCM',
    latitude: 10.775200,
    longitude: 106.693700,
    status: 'APPROVED',
    capabilities: ['COLLECTION'],
    acceptedWasteTypes: [
      { wasteType: 'PLASTIC' },
      { wasteType: 'PAPER' },
      { wasteType: 'GLASS' },
    ],
    collectionProfile: {
      siteType: 'BIN',
      instructions: 'Bỏ rác vào thùng phân loại có dán nhãn.',
      requiresStaffConfirmation: false,
    },
    createdAt: '2026-04-10T06:00:00Z',
    updatedAt: '2026-05-19T08:00:00Z',
  },
];

export const MOCK_TRANSACTIONS: CollectionTransaction[] = [
  {
    id: 'tx-001',
    locationId: 'loc-001',
    location: { id: 'loc-001', name: 'Trạm thu gom Quận 1', address: '123 Nguyễn Huệ, Q.1' },
    userId: 'user-01',
    user: { id: 'user-01', displayName: 'Nguyễn Văn An', email: 'an.nguyen@mail.com' },
    wasteType: 'PLASTIC',
    quantityValue: 3.5,
    quantityUnit: 'KG',
    distanceKm: 0.12,
    status: 'PENDING',
    createdAt: '2026-05-19T06:30:00Z',
  },
  {
    id: 'tx-002',
    locationId: 'loc-002',
    location: { id: 'loc-002', name: 'Thùng rác ĐH Bách Khoa', address: '268 Lý Thường Kiệt, Q.10' },
    userId: 'user-02',
    user: { id: 'user-02', displayName: 'Trần Thị Bích', email: 'bich.tran@mail.com' },
    wasteType: 'PAPER',
    quantityValue: 1.2,
    quantityUnit: 'KG',
    distanceKm: 0.05,
    status: 'VERIFIED',
    pointsAwarded: 60,
    createdAt: '2026-05-19T05:45:00Z',
  },
  {
    id: 'tx-003',
    locationId: 'loc-003',
    location: { id: 'loc-003', name: 'Trung tâm tái chế Q.7', address: '45 Nguyễn Lương Bằng, Q.7' },
    userId: 'user-03',
    user: { id: 'user-03', displayName: 'Lê Minh Châu' },
    wasteType: 'BATTERY',
    quantityValue: 8,
    quantityUnit: 'PIECE',
    distanceKm: 0.30,
    status: 'PENDING',
    createdAt: '2026-05-19T04:15:00Z',
  },
  {
    id: 'tx-004',
    locationId: 'loc-001',
    location: { id: 'loc-001', name: 'Trạm thu gom Quận 1', address: '123 Nguyễn Huệ, Q.1' },
    userId: 'user-04',
    user: { id: 'user-04', displayName: 'Phạm Hồng Đào', email: 'dao.pham@mail.com' },
    wasteType: 'GLASS',
    quantityValue: 2.0,
    quantityUnit: 'KG',
    distanceKm: 0.08,
    status: 'REJECTED',
    rejectionReason: 'Thuỷ tinh bị vỡ, không đảm bảo an toàn.',
    createdAt: '2026-05-18T17:00:00Z',
  },
  {
    id: 'tx-005',
    locationId: 'loc-002',
    location: { id: 'loc-002', name: 'Thùng rác ĐH Bách Khoa', address: '268 Lý Thường Kiệt, Q.10' },
    userId: 'user-05',
    user: { id: 'user-05', displayName: 'Võ Thanh Em' },
    wasteType: 'METAL',
    quantityValue: 5.0,
    quantityUnit: 'KG',
    distanceKm: 0.15,
    status: 'VERIFIED',
    pointsAwarded: 150,
    createdAt: '2026-05-18T14:20:00Z',
  },
  {
    id: 'tx-006',
    locationId: 'loc-003',
    location: { id: 'loc-003', name: 'Trung tâm tái chế Q.7', address: '45 Nguyễn Lương Bằng, Q.7' },
    userId: 'user-01',
    user: { id: 'user-01', displayName: 'Nguyễn Văn An' },
    wasteType: 'PLASTIC',
    quantityValue: 7.8,
    quantityUnit: 'KG',
    distanceKm: 0.22,
    status: 'PENDING',
    createdAt: '2026-05-18T10:30:00Z',
  },
];
