export enum BadgeConditionType {
  FIRST_QUIZ_COMPLETED = 'FIRST_QUIZ_COMPLETED',
  QUIZ_COMPLETED_COUNT = 'QUIZ_COMPLETED_COUNT',
  CLASSIFICATION_COUNT = 'CLASSIFICATION_COUNT',
  DROPOFF_CONFIRMED_COUNT = 'DROPOFF_CONFIRMED_COUNT',
  POINTS_BALANCE_REACHED = 'POINTS_BALANCE_REACHED',
}
